### PR TITLE
Fixed-linting2

### PR DESCRIPTION
**Pull request by Texx45**

### CODE REVIEW

**Review by Mohammedal-abdulhamid — CHANGES_REQUESTED** [review]
good job Terry, I think that you don't need to import prop type in caseStudy. if you fix that please.

**Comment by Texx45** [comment]
I will sort this out Mohammed, those files are not actually on my page I may have committed them before deleting them.

**Comment by Texx45** [comment]
Errors have been revised I was looking on the main branch.

**Review by Mohammedal-abdulhamid — APPROVED** [review]
good job Terry.

**Pull request merged**
